services:

    php.local:
        build:
            context: './docker/php'
            args:
                SYSTEM_TIMEZONE:        ${SYSTEM_TIMEZONE:-Europe/Belgrade}
        environment:
            PHP_XDEBUG_MODE:            ${PHP_XDEBUG_MODE:-debug}
            PHP_XDEBUG_REMOTE_PORT:     ${PHP_XDEBUG_REMOTE_PORT:-9000}
            PHP_XDEBUG_REMOTE_ADDRESS:  ${PHP_XDEBUG_REMOTE_ADDRESS:-host.docker.internal}
            PHP_XDEBUG_IDEKEY:          ${PHP_XDEBUG_IDEKEY:-serverName=localhost}
        env_file:
            - path: './.env'
              required: false
            - path: './.env.local'
              required: false              
        restart: always
        volumes:
            - './:/var/www/html'
        depends_on:
            - mysql.local 
        networks:
            - runopencode_phplib

    mysql.local:
        restart: on-failure
        build:
            context: 'docker/mysql'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: roc
            MYSQL_USER: roc
            MYSQL_PASSWORD: roc
            MYSQL_ROOT_HOST: '%'
        networks:
            - runopencode_phplib
                
networks:
    runopencode_phplib:
                        